### ISSUE TITLE
Could you provide a example of Feature Map Distortion?

### ISSUE THREAD

**Issue by BB88Lee** [huawei-noah/Disout#1]
Thanks for your great work!

I am very curious about the experiments of "Feature Map Distortion" mentioned in paper (for fully connected layer). In code there is only block-wise distortion.

Could you provide a example of Feature Map Distortion?

**Comment by yehuitang** [comment]
Thanks. The implement of element-wise distortion is similar, and you can realize it by slightly modify the file 'disout.py'.
