### ISSUE TITLE
Can anyone help me solve this problem？

### ISSUE THREAD

**Issue by deepdarkfans** [huawei-noah/Disout#10]
Hi, I am a CS master in TYUST, I'm very interested in Disout.
But I could not find this object function in your code
![image](https://user-images.githubusercontent.com/33440182/88061070-9ea0e200-cb99-11ea-819e-8d57b115ce04.png)

![image](https://user-images.githubusercontent.com/33440182/88061276-e0ca2380-cb99-11ea-949e-560f950e0d4d.png)

Can you tell me where it is in the code?
Think you !

**Comment by fengChenHPC** [comment]
please take a look at the code in Vega

**Comment by yehuitang** [comment]
Thanks for your interest. The simplified gradient of this objection function is used, which is discussed in Section 'Optimization of the Distortion'.
