### ISSUE TITLE
Project code

### ISSUE THREAD

**Issue by lambett** [huawei-noah/Disout#13]
Dear Huawei-Noah:

Thank you very much for hoping to reproduce the ideas in the article, but in the process of debugging the code, I found the lack of experiment on fully connected layers code, Can you provide the train_cnn.py and train100_cnn.py code? Thank you very much!

**Comment by yehuitang** [comment]
Thanks for your attention to our work. The implement of disout on fully connected layers is similar with that on convolutional layers. The block size is set to 1.

**Comment by lambett** [comment]
Dear Huawei-Noah:
Thank you for your reply.

**Comment by lambett** [comment]
Dear Huawei-Noah:
Thank you for your reply and note, But when I implemented it according to the ideas you provided, due to personal coding reasons, it was still impossible to realize the content of the FC layer. I really hope that you can provide me part of the project code, thank you very much!
