### ISSUE TITLE
Some inconstency in the paper and code 

### ISSUE THREAD

**Issue by UsedToBe97** [huawei-noah/Disout#2]
https://github.com/huawei-noah/Disout/blob/master/models/resnet.py#L188
![image](https://user-images.githubusercontent.com/33629224/82416785-36585600-9aad-11ea-941d-f3f9c8322fa8.png)
The forwarding for each weight update only does one step distortion update.
https://github.com/huawei-noah/Disout/blob/1c8591f36240b8591691a972c19c7f96134b52a5/disout.py#L106
![image](https://user-images.githubusercontent.com/33629224/82417094-a2d35500-9aad-11ea-8299-292a357f9fd9.png)

But in the paper, it wrote:
![image](https://user-images.githubusercontent.com/33629224/82416930-6dc70280-9aad-11ea-9ae9-400a259f6e6d.png)
![image](https://user-images.githubusercontent.com/33629224/82416942-73244d00-9aad-11ea-91e2-e601365ea6d0.png)
Could anyone explain what does the inconsistency result from?

BTW, some typo in the paper:
![image](https://user-images.githubusercontent.com/33629224/82417180-c0082380-9aad-11ea-8ed5-85af3af0ab5c.png)
I guess it's "l+1" rather than "l+l"

**Comment by yehuitang** [comment]
There may be a misunderstanding about the code. The 'step' function in class 'LinearScheduler' is not to update  weights, but to increase p linearly from 0 to the appointed distortion probability. This a  common strategy and also used in DropBlock.

**Comment by UsedToBe97** [comment]
> There may be a misunderstanding about the code. The 'step' function in class 'LinearScheduler' is not to update weights, but to increase p linearly from 0 to the appointed distortion probability. This a common strategy and also used in DropBlock.

Thanks for clarifying~
But I still don't understand which part of the code updates the distortion via gradient descend, could you please give some guidance? @yehuitang

**Comment by JackieTien97** [comment]
I've got the same question as you. Have you fix where the distortion is updated via gradient descend?
