### ISSUE TITLE
Training configuration

### ISSUE THREAD

**Issue by tzm1003306213** [huawei-noah/Disout#5]
Dear authors,

Thanks for your great work, It's very useful for training CNNs. Would you mind telling me the training configuration so that I can duplicate the method? Another question: I noticed that DropBlock is trained for 270 epochs, while the default training epoch for Disout is 540. Does it make a big difference to the result?

Thanks

**Comment by yehuitang** [comment]
Thanks for your question. For our method, we emperically find that training with more epochs does not aggravate over-fitting. It may even get a more stable result. So using the default configuration is ok.
