### ISSUE TITLE
Could you provide more details of "Experiments on Fully Connected Layers"?

### ISSUE THREAD

**Issue by jiahy0825** [huawei-noah/Disout#7]
Hi,

Thanks for your great work!

I am reproducing your first experiment recently, but even the baseline method I implemented is very different from the results in the paper. (In your paper, Table 1 says the accuracy of conventional CNN method on CIFAR-10 reaches 81.99%)

My implementation is as consistent as possible with the narrative in your section "Implementation details" of "Experiments on Fully Connected Layers". Maybe I missed some details or tricks (such as padding, momentum, etc.), could you provide more information about this experiment?

**Comment by yehuitang** [comment]
The momentum is set to 0.9 following  the common implement of SGD.
