### ISSUE TITLE
Inconsistent training behavior in CIFAR  and ImageNet

### ISSUE THREAD

**Issue by lovekittynine** [huawei-noah/Disout#8]
In the script of resnet.py and train.py where it sets weight_behind of Disout，however in the training process of ImageNet, it resets weight_behind of Disout None. However, why? According to the paper, it should be guided by the ERC value of next layer, and where you use the weights of next layer to approximately compute the gradient of distortion.

**Comment by yehuitang** [comment]
In the code for ImageNet, weight_behind of is not None because of the following code in resnet_imagenet.py
![image](https://user-images.githubusercontent.com/55628940/83318334-75816680-a266-11ea-8f17-7ed8073b855a.png)
