### ISSUE TITLE
May I submit a PR to your repository?

### ISSUE THREAD

**Issue by jiahy0825** [huawei-noah/Disout#9]
Hi,

I'm very interested in your work about Disout. And I reproduced the experiment about conventional CNNs in the paper. I want to submit a PR to your repository, and I wonder if you are willing to accept this. 

Here is my performance of conventional CNNs.

![image](https://user-images.githubusercontent.com/17810795/83609203-81479280-a5b0-11ea-83a6-7f3d5572e601.png)

**Comment by yehuitang** [comment]
Thanks for your interest in our work!  We noticed that a new repo about the code has been opened. Thanks for that.
